### ISSUE TITLE
Add usage instructions 

### ISSUE THREAD

**Issue by HaleTom** [federicobond/solcheck#27]
Would you consider giving a guide to usage if invoked in an invalid way?

Currently I see:

```
$ solcheck
/home/ravi/.local/share/npm/lib/node_modules/minimatch/minimatch.js:116
    throw new TypeError('glob pattern string required')
    ^

TypeError: glob pattern string required
    at new Minimatch (/home/ravi/.local/share/npm/lib/node_modules/minimatch/minimatch.js:116:11)
    at setopts (/home/ravi/.local/share/npm/lib/node_modules/glob/common.js:118:20)
    at new Glob (/home/ravi/.local/share/npm/lib/node_modules/glob/glob.js:135:3)
    at glob (/home/ravi/.local/share/npm/lib/node_modules/glob/glob.js:75:10)
    at lint (/home/ravi/.local/share/npm/lib/node_modules/solcheck/lib/index.js:32:22)
    at main (/home/ravi/.local/share/npm/lib/node_modules/solcheck/lib/index.js:73:5)
    at Object.<anonymous> (/home/ravi/.local/share/npm/lib/node_modules/solcheck/bin/solcheck.js:3:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by federicobond** [comment]
Yes, definitely. Thanks for reporting this.
